# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: gestionActifsDgi
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YTZhY2VlZmZmOWQwOGI4MmI1MGI5MWJmZjY5NjYwNDc0M2QwY2JlYWExODcyYTNkZDEyMWNlOTA2MjU3MDIwZDcwNGNiOWM3ODMyYmZkMGVlOGMyZGFlMzMxMGU0NDVmMjZkYThkYzg3MmQzMDBlYjEyZjNiMDY3OWUwYmE3MmQ=
