export enum TypeMouvement {
  CREATION = 'CREATION',

  MODIFICATION = 'MODIFICATION',

  SUPPRESSION = 'SUPPRESSION',

  AFFECTATION = 'AFFECTATION',

  TRANSFERT = 'TRANSFERT',

  MAINTENANCE = 'MAINTENANCE',
}
