package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ActifAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActifAllPropertiesEquals(Actif expected, Actif actual) {
        assertActifAutoGeneratedPropertiesEquals(expected, actual);
        assertActifAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActifAllUpdatablePropertiesEquals(Actif expected, Actif actual) {
        assertActifUpdatableFieldsEquals(expected, actual);
        assertActifUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActifAutoGeneratedPropertiesEquals(Actif expected, Actif actual) {
        assertThat(actual)
            .as("Verify Actif auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActifUpdatableFieldsEquals(Actif expected, Actif actual) {
        assertThat(actual)
            .as("Verify Actif relevant properties")
            .satisfies(a -> assertThat(a.getCodeInventaire()).as("check codeInventaire").isEqualTo(expected.getCodeInventaire()))
            .satisfies(a -> assertThat(a.getDesignation()).as("check designation").isEqualTo(expected.getDesignation()))
            .satisfies(a -> assertThat(a.getMarque()).as("check marque").isEqualTo(expected.getMarque()))
            .satisfies(a -> assertThat(a.getModele()).as("check modele").isEqualTo(expected.getModele()))
            .satisfies(a -> assertThat(a.getNumeroSerie()).as("check numeroSerie").isEqualTo(expected.getNumeroSerie()))
            .satisfies(a -> assertThat(a.getCodeBarre()).as("check codeBarre").isEqualTo(expected.getCodeBarre()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getEtat()).as("check etat").isEqualTo(expected.getEtat()))
            .satisfies(a -> assertThat(a.getLocalisation()).as("check localisation").isEqualTo(expected.getLocalisation()))
            .satisfies(a -> assertThat(a.getDateAcquisition()).as("check dateAcquisition").isEqualTo(expected.getDateAcquisition()))
            .satisfies(a -> assertThat(a.getValeurAcquisition()).as("check valeurAcquisition").isEqualTo(expected.getValeurAcquisition()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActifUpdatableRelationshipsEquals(Actif expected, Actif actual) {
        assertThat(actual)
            .as("Verify Actif relationships")
            .satisfies(a -> assertThat(a.getCategorie()).as("check categorie").isEqualTo(expected.getCategorie()));
    }
}
