package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AffectationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationAllPropertiesEquals(Affectation expected, Affectation actual) {
        assertAffectationAutoGeneratedPropertiesEquals(expected, actual);
        assertAffectationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationAllUpdatablePropertiesEquals(Affectation expected, Affectation actual) {
        assertAffectationUpdatableFieldsEquals(expected, actual);
        assertAffectationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationAutoGeneratedPropertiesEquals(Affectation expected, Affectation actual) {
        assertThat(actual)
            .as("Verify Affectation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationUpdatableFieldsEquals(Affectation expected, Affectation actual) {
        assertThat(actual)
            .as("Verify Affectation relevant properties")
            .satisfies(a -> assertThat(a.getDateAffectation()).as("check dateAffectation").isEqualTo(expected.getDateAffectation()))
            .satisfies(a -> assertThat(a.getDateRestitution()).as("check dateRestitution").isEqualTo(expected.getDateRestitution()))
            .satisfies(a -> assertThat(a.getNumeroBordereau()).as("check numeroBordereau").isEqualTo(expected.getNumeroBordereau()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationUpdatableRelationshipsEquals(Affectation expected, Affectation actual) {
        assertThat(actual)
            .as("Verify Affectation relationships")
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }
}
