package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AffectationActifAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationActifAllPropertiesEquals(AffectationActif expected, AffectationActif actual) {
        assertAffectationActifAutoGeneratedPropertiesEquals(expected, actual);
        assertAffectationActifAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationActifAllUpdatablePropertiesEquals(AffectationActif expected, AffectationActif actual) {
        assertAffectationActifUpdatableFieldsEquals(expected, actual);
        assertAffectationActifUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationActifAutoGeneratedPropertiesEquals(AffectationActif expected, AffectationActif actual) {
        assertThat(actual)
            .as("Verify AffectationActif auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationActifUpdatableFieldsEquals(AffectationActif expected, AffectationActif actual) {
        assertThat(actual)
            .as("Verify AffectationActif relevant properties")
            .satisfies(a -> assertThat(a.getObservation()).as("check observation").isEqualTo(expected.getObservation()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationActifUpdatableRelationshipsEquals(AffectationActif expected, AffectationActif actual) {
        assertThat(actual)
            .as("Verify AffectationActif relationships")
            .satisfies(a -> assertThat(a.getAffectation()).as("check affectation").isEqualTo(expected.getAffectation()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }
}
