package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BordereauAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBordereauAllPropertiesEquals(Bordereau expected, Bordereau actual) {
        assertBordereauAutoGeneratedPropertiesEquals(expected, actual);
        assertBordereauAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBordereauAllUpdatablePropertiesEquals(Bordereau expected, Bordereau actual) {
        assertBordereauUpdatableFieldsEquals(expected, actual);
        assertBordereauUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBordereauAutoGeneratedPropertiesEquals(Bordereau expected, Bordereau actual) {
        assertThat(actual)
            .as("Verify Bordereau auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBordereauUpdatableFieldsEquals(Bordereau expected, Bordereau actual) {
        assertThat(actual)
            .as("Verify Bordereau relevant properties")
            .satisfies(a -> assertThat(a.getNumero()).as("check numero").isEqualTo(expected.getNumero()))
            .satisfies(a -> assertThat(a.getDateEmission()).as("check dateEmission").isEqualTo(expected.getDateEmission()))
            .satisfies(a -> assertThat(a.getTypeBordereau()).as("check typeBordereau").isEqualTo(expected.getTypeBordereau()))
            .satisfies(a -> assertThat(a.getStatutValidation()).as("check statutValidation").isEqualTo(expected.getStatutValidation()))
            .satisfies(a -> assertThat(a.getDateValidation()).as("check dateValidation").isEqualTo(expected.getDateValidation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBordereauUpdatableRelationshipsEquals(Bordereau expected, Bordereau actual) {
        assertThat(actual)
            .as("Verify Bordereau relationships")
            .satisfies(a -> assertThat(a.getTransfert()).as("check transfert").isEqualTo(expected.getTransfert()))
            .satisfies(a -> assertThat(a.getAffectation()).as("check affectation").isEqualTo(expected.getAffectation()));
    }
}
