package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EquipementRecensementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipementRecensementAllPropertiesEquals(EquipementRecensement expected, EquipementRecensement actual) {
        assertEquipementRecensementAutoGeneratedPropertiesEquals(expected, actual);
        assertEquipementRecensementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipementRecensementAllUpdatablePropertiesEquals(
        EquipementRecensement expected,
        EquipementRecensement actual
    ) {
        assertEquipementRecensementUpdatableFieldsEquals(expected, actual);
        assertEquipementRecensementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipementRecensementAutoGeneratedPropertiesEquals(
        EquipementRecensement expected,
        EquipementRecensement actual
    ) {
        assertThat(actual)
            .as("Verify EquipementRecensement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipementRecensementUpdatableFieldsEquals(EquipementRecensement expected, EquipementRecensement actual) {
        assertThat(actual)
            .as("Verify EquipementRecensement relevant properties")
            .satisfies(a -> assertThat(a.getEtatConstate()).as("check etatConstate").isEqualTo(expected.getEtatConstate()))
            .satisfies(a -> assertThat(a.getDateConstat()).as("check dateConstat").isEqualTo(expected.getDateConstat()))
            .satisfies(a ->
                assertThat(a.getEmplacementConstate()).as("check emplacementConstate").isEqualTo(expected.getEmplacementConstate())
            )
            .satisfies(a -> assertThat(a.getAnomalieConstatee()).as("check anomalieConstatee").isEqualTo(expected.getAnomalieConstatee()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipementRecensementUpdatableRelationshipsEquals(
        EquipementRecensement expected,
        EquipementRecensement actual
    ) {
        assertThat(actual)
            .as("Verify EquipementRecensement relationships")
            .satisfies(a -> assertThat(a.getRecensement()).as("check recensement").isEqualTo(expected.getRecensement()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }
}
