package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FournisseurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFournisseurAllPropertiesEquals(Fournisseur expected, Fournisseur actual) {
        assertFournisseurAutoGeneratedPropertiesEquals(expected, actual);
        assertFournisseurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFournisseurAllUpdatablePropertiesEquals(Fournisseur expected, Fournisseur actual) {
        assertFournisseurUpdatableFieldsEquals(expected, actual);
        assertFournisseurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFournisseurAutoGeneratedPropertiesEquals(Fournisseur expected, Fournisseur actual) {
        assertThat(actual)
            .as("Verify Fournisseur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFournisseurUpdatableFieldsEquals(Fournisseur expected, Fournisseur actual) {
        assertThat(actual)
            .as("Verify Fournisseur relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getContact()).as("check contact").isEqualTo(expected.getContact()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelephone()).as("check telephone").isEqualTo(expected.getTelephone()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFournisseurUpdatableRelationshipsEquals(Fournisseur expected, Fournisseur actual) {
        // empty method
    }
}
