package com.dgi.gestionactifs.domain;

import static com.dgi.gestionactifs.domain.AssertUtils.zonedDateTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class HistoriqueActionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueActionAllPropertiesEquals(HistoriqueAction expected, HistoriqueAction actual) {
        assertHistoriqueActionAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoriqueActionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueActionAllUpdatablePropertiesEquals(HistoriqueAction expected, HistoriqueAction actual) {
        assertHistoriqueActionUpdatableFieldsEquals(expected, actual);
        assertHistoriqueActionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueActionAutoGeneratedPropertiesEquals(HistoriqueAction expected, HistoriqueAction actual) {
        assertThat(actual)
            .as("Verify HistoriqueAction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueActionUpdatableFieldsEquals(HistoriqueAction expected, HistoriqueAction actual) {
        assertThat(actual)
            .as("Verify HistoriqueAction relevant properties")
            .satisfies(a ->
                assertThat(a.getDateAction())
                    .as("check dateAction")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getDateAction())
            )
            .satisfies(a -> assertThat(a.getTypeAction()).as("check typeAction").isEqualTo(expected.getTypeAction()))
            .satisfies(a -> assertThat(a.getEntiteCiblee()).as("check entiteCiblee").isEqualTo(expected.getEntiteCiblee()))
            .satisfies(a -> assertThat(a.getAncienneValeur()).as("check ancienneValeur").isEqualTo(expected.getAncienneValeur()))
            .satisfies(a -> assertThat(a.getNouvelleValeur()).as("check nouvelleValeur").isEqualTo(expected.getNouvelleValeur()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueActionUpdatableRelationshipsEquals(HistoriqueAction expected, HistoriqueAction actual) {
        // empty method
    }
}
