package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InterventionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterventionAllPropertiesEquals(Intervention expected, Intervention actual) {
        assertInterventionAutoGeneratedPropertiesEquals(expected, actual);
        assertInterventionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterventionAllUpdatablePropertiesEquals(Intervention expected, Intervention actual) {
        assertInterventionUpdatableFieldsEquals(expected, actual);
        assertInterventionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterventionAutoGeneratedPropertiesEquals(Intervention expected, Intervention actual) {
        assertThat(actual)
            .as("Verify Intervention auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterventionUpdatableFieldsEquals(Intervention expected, Intervention actual) {
        assertThat(actual)
            .as("Verify Intervention relevant properties")
            .satisfies(a -> assertThat(a.getDateDeclaration()).as("check dateDeclaration").isEqualTo(expected.getDateDeclaration()))
            .satisfies(a -> assertThat(a.getTypeIntervention()).as("check typeIntervention").isEqualTo(expected.getTypeIntervention()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterventionUpdatableRelationshipsEquals(Intervention expected, Intervention actual) {
        assertThat(actual)
            .as("Verify Intervention relationships")
            .satisfies(a -> assertThat(a.getPanne()).as("check panne").isEqualTo(expected.getPanne()))
            .satisfies(a -> assertThat(a.getPlannings()).as("check plannings").isEqualTo(expected.getPlannings()));
    }
}
