package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InventaireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireAllPropertiesEquals(Inventaire expected, Inventaire actual) {
        assertInventaireAutoGeneratedPropertiesEquals(expected, actual);
        assertInventaireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireAllUpdatablePropertiesEquals(Inventaire expected, Inventaire actual) {
        assertInventaireUpdatableFieldsEquals(expected, actual);
        assertInventaireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireAutoGeneratedPropertiesEquals(Inventaire expected, Inventaire actual) {
        assertThat(actual)
            .as("Verify Inventaire auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireUpdatableFieldsEquals(Inventaire expected, Inventaire actual) {
        assertThat(actual)
            .as("Verify Inventaire relevant properties")
            .satisfies(a -> assertThat(a.getNomFichier()).as("check nomFichier").isEqualTo(expected.getNomFichier()))
            .satisfies(a -> assertThat(a.getDateImport()).as("check dateImport").isEqualTo(expected.getDateImport()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireUpdatableRelationshipsEquals(Inventaire expected, Inventaire actual) {
        assertThat(actual)
            .as("Verify Inventaire relationships")
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }
}
