package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MaintenanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceAllPropertiesEquals(Maintenance expected, Maintenance actual) {
        assertMaintenanceAutoGeneratedPropertiesEquals(expected, actual);
        assertMaintenanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceAllUpdatablePropertiesEquals(Maintenance expected, Maintenance actual) {
        assertMaintenanceUpdatableFieldsEquals(expected, actual);
        assertMaintenanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceAutoGeneratedPropertiesEquals(Maintenance expected, Maintenance actual) {
        assertThat(actual)
            .as("Verify Maintenance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceUpdatableFieldsEquals(Maintenance expected, Maintenance actual) {
        assertThat(actual)
            .as("Verify Maintenance relevant properties")
            .satisfies(a -> assertThat(a.getTypeMaintenance()).as("check typeMaintenance").isEqualTo(expected.getTypeMaintenance()))
            .satisfies(a -> assertThat(a.getDatePanne()).as("check datePanne").isEqualTo(expected.getDatePanne()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getCompteRendu()).as("check compteRendu").isEqualTo(expected.getCompteRendu()))
            .satisfies(a -> assertThat(a.getDateCloture()).as("check dateCloture").isEqualTo(expected.getDateCloture()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceUpdatableRelationshipsEquals(Maintenance expected, Maintenance actual) {
        assertThat(actual)
            .as("Verify Maintenance relationships")
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }
}
