package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PanneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPanneAllPropertiesEquals(Panne expected, Panne actual) {
        assertPanneAutoGeneratedPropertiesEquals(expected, actual);
        assertPanneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPanneAllUpdatablePropertiesEquals(Panne expected, Panne actual) {
        assertPanneUpdatableFieldsEquals(expected, actual);
        assertPanneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPanneAutoGeneratedPropertiesEquals(Panne expected, Panne actual) {
        assertThat(actual)
            .as("Verify Panne auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPanneUpdatableFieldsEquals(Panne expected, Panne actual) {
        assertThat(actual)
            .as("Verify Panne relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDateDeclaration()).as("check dateDeclaration").isEqualTo(expected.getDateDeclaration()))
            .satisfies(a -> assertThat(a.getStatutPanne()).as("check statutPanne").isEqualTo(expected.getStatutPanne()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPanneUpdatableRelationshipsEquals(Panne expected, Panne actual) {
        assertThat(actual)
            .as("Verify Panne relationships")
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }
}
