package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlanningMaintenanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningMaintenanceAllPropertiesEquals(PlanningMaintenance expected, PlanningMaintenance actual) {
        assertPlanningMaintenanceAutoGeneratedPropertiesEquals(expected, actual);
        assertPlanningMaintenanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningMaintenanceAllUpdatablePropertiesEquals(PlanningMaintenance expected, PlanningMaintenance actual) {
        assertPlanningMaintenanceUpdatableFieldsEquals(expected, actual);
        assertPlanningMaintenanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningMaintenanceAutoGeneratedPropertiesEquals(PlanningMaintenance expected, PlanningMaintenance actual) {
        assertThat(actual)
            .as("Verify PlanningMaintenance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningMaintenanceUpdatableFieldsEquals(PlanningMaintenance expected, PlanningMaintenance actual) {
        assertThat(actual)
            .as("Verify PlanningMaintenance relevant properties")
            .satisfies(a -> assertThat(a.getDatePrevue()).as("check datePrevue").isEqualTo(expected.getDatePrevue()))
            .satisfies(a -> assertThat(a.getPeriodicite()).as("check periodicite").isEqualTo(expected.getPeriodicite()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningMaintenanceUpdatableRelationshipsEquals(PlanningMaintenance expected, PlanningMaintenance actual) {
        assertThat(actual)
            .as("Verify PlanningMaintenance relationships")
            .satisfies(a -> assertThat(a.getInterventions()).as("check interventions").isEqualTo(expected.getInterventions()));
    }
}
