package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RecensementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecensementAllPropertiesEquals(Recensement expected, Recensement actual) {
        assertRecensementAutoGeneratedPropertiesEquals(expected, actual);
        assertRecensementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecensementAllUpdatablePropertiesEquals(Recensement expected, Recensement actual) {
        assertRecensementUpdatableFieldsEquals(expected, actual);
        assertRecensementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecensementAutoGeneratedPropertiesEquals(Recensement expected, Recensement actual) {
        assertThat(actual)
            .as("Verify Recensement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecensementUpdatableFieldsEquals(Recensement expected, Recensement actual) {
        assertThat(actual)
            .as("Verify Recensement relevant properties")
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecensementUpdatableRelationshipsEquals(Recensement expected, Recensement actual) {
        // empty method
    }
}
