package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceDgiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceDgiAllPropertiesEquals(ServiceDgi expected, ServiceDgi actual) {
        assertServiceDgiAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceDgiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceDgiAllUpdatablePropertiesEquals(ServiceDgi expected, ServiceDgi actual) {
        assertServiceDgiUpdatableFieldsEquals(expected, actual);
        assertServiceDgiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceDgiAutoGeneratedPropertiesEquals(ServiceDgi expected, ServiceDgi actual) {
        assertThat(actual)
            .as("Verify ServiceDgi auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceDgiUpdatableFieldsEquals(ServiceDgi expected, ServiceDgi actual) {
        assertThat(actual)
            .as("Verify ServiceDgi relevant properties")
            .satisfies(a -> assertThat(a.getNomService()).as("check nomService").isEqualTo(expected.getNomService()))
            .satisfies(a -> assertThat(a.getChefService()).as("check chefService").isEqualTo(expected.getChefService()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceDgiUpdatableRelationshipsEquals(ServiceDgi expected, ServiceDgi actual) {
        // empty method
    }
}
