package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransfertAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertAllPropertiesEquals(Transfert expected, Transfert actual) {
        assertTransfertAutoGeneratedPropertiesEquals(expected, actual);
        assertTransfertAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertAllUpdatablePropertiesEquals(Transfert expected, Transfert actual) {
        assertTransfertUpdatableFieldsEquals(expected, actual);
        assertTransfertUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertAutoGeneratedPropertiesEquals(Transfert expected, Transfert actual) {
        assertThat(actual)
            .as("Verify Transfert auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertUpdatableFieldsEquals(Transfert expected, Transfert actual) {
        assertThat(actual)
            .as("Verify Transfert relevant properties")
            .satisfies(a -> assertThat(a.getDateDemande()).as("check dateDemande").isEqualTo(expected.getDateDemande()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getCommentaireRejet()).as("check commentaireRejet").isEqualTo(expected.getCommentaireRejet()))
            .satisfies(a -> assertThat(a.getDateTraitement()).as("check dateTraitement").isEqualTo(expected.getDateTraitement()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertUpdatableRelationshipsEquals(Transfert expected, Transfert actual) {
        assertThat(actual)
            .as("Verify Transfert relationships")
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }
}
