package com.dgi.gestionactifs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransfertActifAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertActifAllPropertiesEquals(TransfertActif expected, TransfertActif actual) {
        assertTransfertActifAutoGeneratedPropertiesEquals(expected, actual);
        assertTransfertActifAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertActifAllUpdatablePropertiesEquals(TransfertActif expected, TransfertActif actual) {
        assertTransfertActifUpdatableFieldsEquals(expected, actual);
        assertTransfertActifUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertActifAutoGeneratedPropertiesEquals(TransfertActif expected, TransfertActif actual) {
        assertThat(actual)
            .as("Verify TransfertActif auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertActifUpdatableFieldsEquals(TransfertActif expected, TransfertActif actual) {
        assertThat(actual)
            .as("Verify TransfertActif relevant properties")
            .satisfies(a -> assertThat(a.getObservation()).as("check observation").isEqualTo(expected.getObservation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertActifUpdatableRelationshipsEquals(TransfertActif expected, TransfertActif actual) {
        assertThat(actual)
            .as("Verify TransfertActif relationships")
            .satisfies(a -> assertThat(a.getTransfert()).as("check transfert").isEqualTo(expected.getTransfert()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }
}
